[project]
name = "interpreter"
version = "1.0.0"
description = "Langage de programmation expérimental inspiré de Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.1",
]
