[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pylpex"
version = "1.0.2"
description = "Langage de programmation expérimental inspiré de Python."
readme = "README.md"
requires-python = ">=3.13"
authors = [
  {name="Guillaume Foucaud", email="guillaumefoucaudmath@gmail.com"}
]
license = "MIT"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
    "ipykernel>=7.0.1",
]

[project.scripts]
pylpex = "pylpex.main:main"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]


